from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from ..errors import ERROR_CATALOG


class ContextErrorCode(str, Enum):
    REQUEST_INVALID = "CONTEXT_REQUEST_INVALID"
    IDENTIFIER_INVALID = "CONTEXT_IDENTIFIER_INVALID"
    SOURCE_INVALID = "CONTEXT_SOURCE_INVALID"
    DELETE_CONFIRMATION_INVALID = "CONTEXT_DELETE_CONFIRMATION_INVALID"
    POINT_KEY_INVALID = "CONTEXT_POINT_KEY_INVALID"
    EMBEDDING_INVALID = "CONTEXT_EMBEDDING_INVALID"
    FILTER_INVALID = "CONTEXT_FILTER_INVALID"
    LIMIT_EXCEEDED = "CONTEXT_LIMIT_EXCEEDED"
    GRAPH_START_REQUIRED = "CONTEXT_GRAPH_START_REQUIRED"
    GRAPH_DIRECTION_INVALID = "CONTEXT_GRAPH_DIRECTION_INVALID"
    RANKING_WEIGHTS_INVALID = "CONTEXT_RANKING_WEIGHTS_INVALID"
    RESOURCE_NAMESPACE_MISMATCH = "CONTEXT_RESOURCE_NAMESPACE_MISMATCH"
    COLLECTION_NOT_FOUND = "CONTEXT_COLLECTION_NOT_FOUND"
    OPERATION_NOT_FOUND = "CONTEXT_OPERATION_NOT_FOUND"
    COLLECTION_NOT_READY = "CONTEXT_COLLECTION_NOT_READY"
    TEXT_COLUMN_REQUIRED = "CONTEXT_TEXT_COLUMN_REQUIRED"
    GRAPH_NOT_READY = "CONTEXT_GRAPH_NOT_READY"
    SOURCE_KEY_ALIGNMENT_INVALID = "CONTEXT_SOURCE_KEY_ALIGNMENT_INVALID"
    CAPABILITY_UNAVAILABLE = "CONTEXT_CAPABILITY_UNAVAILABLE"
    SOURCE_KEY_NOT_FOUND = "CONTEXT_SOURCE_KEY_NOT_FOUND"
    SOURCE_VECTOR_INVALID = "CONTEXT_SOURCE_VECTOR_INVALID"
    FILTER_REGISTRATION_CONFLICT = "CONTEXT_FILTER_REGISTRATION_CONFLICT"
    POINT_CURSOR_INVALID = "CONTEXT_POINT_CURSOR_INVALID"
    RECALL_UNAVAILABLE = "CONTEXT_RECALL_UNAVAILABLE"
    COLLECTION_NAME_CONFLICT = "CONTEXT_COLLECTION_NAME_CONFLICT"
    PREFLIGHT_BLOCKED = "CONTEXT_PREFLIGHT_BLOCKED"
    OPERATION_CONFLICT = "CONTEXT_OPERATION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "CONTEXT_IDEMPOTENCY_CONFLICT"
    OPERATION_NOT_CANCELLABLE = "CONTEXT_OPERATION_NOT_CANCELLABLE"
    OPERATION_NOT_RETRYABLE = "CONTEXT_OPERATION_NOT_RETRYABLE"
    OPERATION_CANCELLED = "CONTEXT_OPERATION_CANCELLED"
    ONBOARDING_NOT_ELIGIBLE = "CONTEXT_ONBOARDING_NOT_ELIGIBLE"
    ONBOARDING_NOT_AVAILABLE = "CONTEXT_ONBOARDING_NOT_AVAILABLE"
    RUNTIME_UNSUPPORTED = "CONTEXT_RUNTIME_UNSUPPORTED"
    EXTENSION_UNAVAILABLE = "CONTEXT_EXTENSION_UNAVAILABLE"
    SOURCE_TABLE_UNSUPPORTED = "CONTEXT_SOURCE_TABLE_UNSUPPORTED"
    SOURCE_KEY_REQUIRED = "CONTEXT_SOURCE_KEY_REQUIRED"
    SOURCE_KEY_TYPE_UNSUPPORTED = "CONTEXT_SOURCE_KEY_TYPE_UNSUPPORTED"
    SOURCE_KEY_TEXT_CONSTRAINT_REQUIRED = "CONTEXT_SOURCE_KEY_TEXT_CONSTRAINT_REQUIRED"
    SOURCE_PRIVILEGE_REQUIRED = "CONTEXT_SOURCE_PRIVILEGE_REQUIRED"
    VECTOR_COLUMN_MISSING = "CONTEXT_VECTOR_COLUMN_MISSING"
    VECTOR_COLUMN_CONFLICT = "CONTEXT_VECTOR_COLUMN_CONFLICT"
    VECTOR_TYPE_UNSUPPORTED = "CONTEXT_VECTOR_TYPE_UNSUPPORTED"
    VECTOR_NULLABLE = "CONTEXT_VECTOR_NULLABLE"
    VECTOR_DIMENSION_INVALID = "CONTEXT_VECTOR_DIMENSION_INVALID"
    COSINE_ZERO_VECTOR = "CONTEXT_COSINE_ZERO_VECTOR"
    RESULT_COLUMN_INVALID = "CONTEXT_RESULT_COLUMN_INVALID"
    FILTER_COLUMN_INVALID = "CONTEXT_FILTER_COLUMN_INVALID"
    JSONB_FILTER_PATH_INVALID = "CONTEXT_JSONB_FILTER_PATH_INVALID"
    RESERVED_FILTER_CONFLICT = "CONTEXT_RESERVED_FILTER_CONFLICT"
    TEXT_COLUMN_INVALID = "CONTEXT_TEXT_COLUMN_INVALID"
    HNSW_UNSUPPORTED = "CONTEXT_HNSW_UNSUPPORTED"
    INDEX_CONFLICT = "CONTEXT_INDEX_CONFLICT"
    MEMORY_PRESSURE = "CONTEXT_MEMORY_PRESSURE"
    PGVECTOR_SOURCE = "CONTEXT_PGVECTOR_SOURCE"
    UNSUPPORTED_VECTOR_TYPE = "CONTEXT_UNSUPPORTED_VECTOR_TYPE"


@dataclass(frozen=True, slots=True)
class ContextErrorDescriptor:
    status_code: int
    message: str
    safe_detail_fields: tuple[str, ...] = ()
    retryable: bool = False
    conflict: bool = False
    availability: bool = False


CONTEXT_ERROR_CATALOG: dict[ContextErrorCode, ContextErrorDescriptor] = {
    code: ContextErrorDescriptor(
        status_code=ERROR_CATALOG[code.value].http_status,
        message=ERROR_CATALOG[code.value].message,
        safe_detail_fields=tuple(sorted(ERROR_CATALOG[code.value].safe_detail_fields)),
        retryable=ERROR_CATALOG[code.value].retry_class
        in {"bounded_retry", "dependency_retry", "after_delay"},
        conflict=ERROR_CATALOG[code.value].http_status == 409,
        availability=(
            "UNAVAILABLE" in code.value
            or "NOT_READY" in code.value
            or code is ContextErrorCode.MEMORY_PRESSURE
        ),
    )
    for code in ContextErrorCode
}

if set(CONTEXT_ERROR_CATALOG) != set(ContextErrorCode):
    raise RuntimeError("global error catalog must define every ContextErrorCode exactly once")


__all__ = [
    "CONTEXT_ERROR_CATALOG",
    "ContextErrorCode",
    "ContextErrorDescriptor",
]
